server:
  port: 8888

# MyApiLogAspect 中是否过滤返回系统内容错误
myApiLogAspect:
  isFilterInsideError: false 

# 文件存储路径  
file-upload:
  #文件根目录
  upload-path: E:/MyApiDemo/file/
      #服务器访问地址
  server-file-path: /files/**
     #文件存放路径
  server-save-file-path: /files/
     #接口文件存放地址
  api-log-path: ${file-upload.upload-path}/apiLog/